name: Update Stats

on:
  #push:
  #pull_request:
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Update Latest Release, .NET, and NuGet Version in README
      run: |
        # Define the new version numbers
        $NewReleaseVersion = "v2.0"  # Replace with your dynamic version variable for release
        $NewDotNetVersion = "${{ secrets.DOTNET_VERSION }}"    # Replace with your dynamic version variable for .NET
        $NewDotNetVersion = $NewDotNetVersion.Replace(".*", "")
        echo ".net ver = " + $NewDotNetVersion
        $NewNugetVersion = "v3.0"    # Replace with your dynamic version variable for NuGet

        # Patterns to identify the badge lines
        $ReleasePattern = '\!\[Static Badge\]\(https:\/\/img\.shields\.io\/badge\/Latest_Release-v[0-9]+(\.[0-9]+){0,2}-blue\)'
        $DotNetPattern = '\!\[Static Badge\]\(https:\/\/img\.shields\.io\/badge\/\.NET-[0-9]+(\.[0-9]+){0,2}-darkblue\)'
        $NugetPattern = '\!\[Static Badge\]\(https:\/\/img\.shields\.io\/badge\/NuGet_Package-v[0-9]+(\.[0-9]+){0,2}-blue\)'

        # New badge lines with updated versions
        $ReleaseReplacement = "![Static Badge](https://img.shields.io/badge/Latest_Release-$NewReleaseVersion-blue)"
        $DotNetReplacement = "![Static Badge](https://img.shields.io/badge/.NET-$NewDotNetVersion-darkblue)"
        $NugetReplacement = "![Static Badge](https://img.shields.io/badge/NuGet_Package-$NewNugetVersion-blue)"

        # Update the README.md
        $readmeContent = Get-Content README.md
        $readmeContent -replace $ReleasePattern, $ReleaseReplacement -replace $DotNetPattern, $DotNetReplacement -replace $NugetPattern, $NugetReplacement | Set-Content README.md

        # Check if there are changes and commit them
        if (git status --porcelain) {
          git config --global user.name 'PrimeEagle'
          git config --global user.email 'misc@hiddendragon.com'
          git add README.md
          git commit -m "Update version badges in README"
          git push
        }
      shell: pwsh
